### ISSUE TITLE
Debugging console exits and the connect script hangs

### ISSUE THREAD

**Issue by user202729** [user202729/plover-debugging-console#1]
Sometimes this happens. No idea why.

**Comment by lf-** [comment]
Seems consistently reproducible on my machine with `jupyter console --existing $(cat /tmp/$USER/plover_debugging_console_path)`. I'm guessing it's something funny on the server side, but I have no idea what.

**Comment by user202729** [comment]
Not reproducible for me.

(last line after exiting is always "keeping kernel alive")

Try running plover with `--debug log` or see the log file to see if there's error stack trace or something there.

**Comment by lf-** [comment]
```
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://{ip redacted}:45549
[ZMQTerminalIPythonApp] Connecting to: tcp://{ip redacted}:45549
[ZMQTerminalIPythonApp] connecting shell channel to tcp://{ip redacted}:46239
[ZMQTerminalIPythonApp] Connecting to: tcp://{ip redacted}:46239
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://{ip redacted}:47017
[ZMQTerminalIPythonApp] Connecting to: tcp://{ip redacted}:47017
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://{ip redacted}:32879
[ZMQTerminalIPythonApp] connecting control channel to tcp://{ip redacted}:38197
[ZMQTerminalIPythonApp] Connecting to: tcp://{ip redacted}:38197
```

I have wiresharked it, and it seems like the symptom is that it repeatedly tries to connect to the stdin port from the JSON file, which is indeed not listening! I don't know if this is actually *the* problem, but it is a problem.

**Comment by lf-** [comment]
Ah, yeah, some interesting stuff in Plover log:

```
/usr/lib/python3.10/site-packages/traitlets/traitlets.py:1266: RuntimeWarning: Kernel only supports one shell stream. Additional streams will be ignored.
  c(event)
2022-01-01 18:42:48,386 [Dummy-1] INFO: loaded 3 dictionaries in 0.421s
debugpy_stream undefined, debugging will not be enabled
ERROR:tornado.application:Exception in callback functools.partial(<bound method IPythonBackgroundKernelWrapper._start_kernel of <background_zmq_ipython.kernel.IPythonBackgroundKernelWrapper object at 0x7f78a11c3b20>>)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/lf/.local/lib/python3.10/site-packages/background_zmq_ipython/kernel.py", line 284, in _start_kernel
    self._kernel.start()
  File "/home/lf/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 178, in start
    super(IPythonKernel, self).start()
  File "/home/lf/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 489, in start
    self.control_stream.on_recv(self.dispatch_control, copy=False)
AttributeError: 'NoneType' object has no attribute 'on_recv'

```

**Comment by user202729** [comment]
`control_stream`... https://github.com/albertz/background-zmq-ipython/pull/11/files looks related.

No idea if you're using ipykernel 6 or not, but try running background_zmq_ipython from the GitHub latest version.

**Comment by lf-** [comment]
Yup, that was part of it, and so was https://github.com/jupyter/jupyter_console/pull/258 🙃 . Will let you know if I get the other random connection failure issue.
